Fixed issue 224: Remove getCause overrides in Exceptions.
RepositoryException overrides getCause but not initCause. The getCause
method only returns a cause passed to the constructor, and not a cause
passed to initCause. This is because the constructors and getCause use
a local field, but initCause is not overridden and returns the null
cause from the super class.

The same is true in ConnectorManagerException, and subclasses also
assign the local rootCause field, rather than setting the cause in the
Throwable superclass.

Also, RepositoryException and ConnectorManagerException override
getMessage, but the override didn't account for the copying of the
cause.toString as the default message, so that instead of a message of
"root cause", you would get

      java.lang.Exception: root cause: root cause

M    projects/connector-manager/source/java/com/google/enterprise/connector/instantiator/InstantiatorException.java
M    projects/connector-manager/source/java/com/google/enterprise/connector/pusher/FeedException.java
M    projects/connector-manager/source/java/com/google/enterprise/connector/pusher/PushException.java
M    projects/connector-manager/source/java/com/google/enterprise/connector/common/PropertiesException.java
M    projects/connector-manager/source/java/com/google/enterprise/connector/persist/ConnectorNotFoundException.java
M    projects/connector-manager/source/java/com/google/enterprise/connector/persist/ConnectorTypeNotFoundException.java
M    projects/connector-manager/source/java/com/google/enterprise/connector/persist/ConnectorExistsException.java
M    projects/connector-manager/source/java/com/google/enterprise/connector/persist/PersistentStoreException.java
M    projects/connector-manager/source/java/com/google/enterprise/connector/manager/ConnectorManagerException.java
M    projects/connector-manager/source/java/com/google/enterprise/connector/spi/RepositoryException.java
AM   projects/connector-manager/source/javatests/com/google/enterprise/connector/spi/RepositoryExceptionTest.java