Fix to use well formed XHTML.  Currently color value not quoted and causing a SAXParsException if filtered:
org.xml.sax.SAXParseException: Open quote is expected for attribute "{1}"
  associated with an  element type  "color".

M java/com/google/enterprise/connector/spi/SimpleConnectorType.java:
  - Quoted the color value used in the form snippet.

M javatests/com/google/enterprise/connector/spi/SimpleConnectorTypeTest.java
  - Changed the expected value to look for the quoted color value.